dist: trusty
language: node_js
node_js:
  - "9"

# 确保 npm 版本为6.0以上
before_install: if [[ `npm -v` != 6* ]]; then npm i -g npm@6; fi
# 安装依赖包
install:
    - npm install
script:
    - npm run build

cache:
  directories:
    - "node_modules"

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: dist
  on:
    branch: master